# Generated by Django 5.1.4 on 2024-12-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='срок сдачи'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('начальный', 'начальный'), ('средний', 'средний'), ('продвинутый', 'продвинутый')], default='начальный', max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('одиночный_выбор', 'одиночный_выбор'), ('множественный_выбор', 'множественный_выбор'), ('текстовый_ответ', 'текстовый_ответ')], default='одиночный_выбор', max_length=20)),
                ('options', models.CharField(blank=True, max_length=32, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=32, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='вопросы', to='store.exam')),
            ],
        ),
    ]
