# Generated by Django 5.1.4 on 2024-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_assignment_due_date_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(verbose_name='дата выдачи'),
        ),
    ]
