# Generated by Django 5.1.4 on 2024-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_certificate_issued_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestions',
            name='correct_answer',
            field=models.CharField(default=1, max_length=32, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
    ]
