# Generated by Django 5.1.4 on 2024-12-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_review_course_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course',
            new_name='course_assignment',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='curses',
            new_name='course_certificate',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='student',
            new_name='student_certificate',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='course_price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='course',
            new_name='course_exam',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='course_url',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DateTimeField(verbose_name='продолжительность'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='проходной_балл'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=32, verbose_name='название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
