# Generated by Django 5.1.4 on 2024-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_course_assignment_course_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(),
        ),
    ]
