# Generated by Django 5.1.4 on 2024-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_certificate_certificate_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='проходной балл'),
        ),
        migrations.AlterField(
            model_name='examquestions',
            name='question_type',
            field=models.CharField(choices=[('одиночный выбор', 'одиночный выбор'), ('множественный  выбор', 'множественный выбор'), ('текстовый ответ', 'текстовый ответ')], default='одиночный_выбор', max_length=20),
        ),
    ]
