# Generated by Django 5.1.4 on 2024-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_course_lesson_alter_exam_passing_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestions',
            name='options',
        ),
        migrations.AddField(
            model_name='examquestions',
            name='question_option',
            field=models.CharField(choices=[('a)', 'a)'), ('b)', 'b)'), ('c)', 'c)'), ('d)', 'b)')], default='a)', max_length=32),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='user_answer',
            field=models.CharField(blank=True, choices=[('a)', 'a)'), ('b)', 'b)'), ('c)', 'c)'), ('d)', 'b)')], max_length=32, null=True),
        ),
    ]
