# Generated by Django 5.1.4 on 2024-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_examquestions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestions',
            name='question_option',
            field=models.CharField(choices=[('a)', 'a)'), ('b)', 'b)'), ('c)', 'c)'), ('d)', 'd)')], default='a)', max_length=32),
        ),
        migrations.AlterField(
            model_name='examquestions',
            name='user_answer',
            field=models.CharField(blank=True, choices=[('a)', 'a)'), ('b)', 'b)'), ('c)', 'c)'), ('d)', 'd)')], max_length=32, null=True),
        ),
    ]
